import { API_ROUTES } from "../../../shared/constants/apiRoutesConstants";

export const API_URL = import.meta.env.VITE_REACT_APP_API_URL;

export const ENDPOINTS = {
  GROUPS: `/${API_ROUTES.GROUPS.GROUPS_BASE}`,
  GROUP_TRANSACTIONS: API_ROUTES.GROUPS.TRANSACTIONS,
  GROUP_CURRENCY: `/${API_ROUTES.GROUPS.CURRENCY}`,
  USERS: `/${API_ROUTES.USERS.USERS_BASE}`,
  USERS_BY_GROUP_CODE: API_ROUTES.USERS.BY_GROUP_CODE,
  EXPENSES: `/${API_ROUTES.EXPENSES.EXPENSES_BASE}`,
  PAYMENTS: `/${API_ROUTES.PAYMENTS.PAYMENTS_BASE}`,
  SETTLEMENTS: `/${API_ROUTES.SETTLEMENTS.SETTLEMENTS_BASE}`,
};
