import { API_ROUTES } from "../../../shared/constants/apiRoutesConstants";

export const API_URL = import.meta.env.VITE_REACT_APP_API_URL;

export const ENDPOINTS = {
  GROUPS: `${API_ROUTES.GROUPS.BASE}`,
  GROUP_TRANSACTIONS: `${API_ROUTES.GROUPS.TRANSACTIONS}`,
  GROUP_CURRENCY: `${API_ROUTES.GROUPS.CURRENCY}`,
  STORED_GROUP_NAMES: `${API_ROUTES.GROUPS.STORED_GROUP_NAMES}`,

  USERS: `${API_ROUTES.USERS.BASE}`,
  USERS_BY_GROUP_CODE: `${API_ROUTES.USERS.BY_GROUP_CODE}`,

  EXPENSES: `${API_ROUTES.EXPENSES.BASE}`,
  EXPENSES_TOTAL: `${API_ROUTES.EXPENSES.TOTAL}`,

  PAYMENTS: `${API_ROUTES.PAYMENTS.BASE}`,
  SETTLEMENTS: `${API_ROUTES.SETTLEMENTS.BASE}`,
};
