import createRoute from "../utils/route/createRoute.js";
import CLIENT_STATIC_ROUTES from "./clientStaticRoutesConstants.js";

const TO_EXPENSE = {
  CREATE: CLIENT_STATIC_ROUTES.CREATE_EXPENSE,
  UPDATE: createRoute(CLIENT_STATIC_ROUTES.UPDATE_EXPENSE),
  DETAILS: createRoute(CLIENT_STATIC_ROUTES.EXPENSE_DETAILS),
};

const TO_PAYMENT = {
  CREATE: CLIENT_STATIC_ROUTES.CREATE_PAYMENT,
  UPDATE: createRoute(CLIENT_STATIC_ROUTES.UPDATE_PAYMENT),
  DETAILS: createRoute(CLIENT_STATIC_ROUTES.PAYMENT_DETAILS),
};

const TO_MEMBERS = {
  CREATE: CLIENT_STATIC_ROUTES.CREATE_MEMBERS,
  DETAILS: createRoute(CLIENT_STATIC_ROUTES.MEMBER_DETAILS),
  TRANSACTION_HISTORY: createRoute(
    CLIENT_STATIC_ROUTES.MEMBER_TRANSACTION_HISTORY,
  ),
};

const TO_GROUP_ACTIONS = {
  JOIN_DE: createRoute(CLIENT_STATIC_ROUTES.JOIN_GROUP_DE),
  JOIN_EN: createRoute(CLIENT_STATIC_ROUTES.JOIN_GROUP_EN),
  TUTORIAL: createRoute(CLIENT_STATIC_ROUTES.TUTORIAL),
  LEAVE: createRoute(CLIENT_STATIC_ROUTES.LEAVE_GROUP),
  SHARE: createRoute(CLIENT_STATIC_ROUTES.SHARE_GROUP),
};

const TO_STATIC = {
  HOME: CLIENT_STATIC_ROUTES.HOME,
  INSTANT_SPLIT: CLIENT_STATIC_ROUTES.INSTANT_SPLIT,
  SETTLE_EXPENSES: CLIENT_STATIC_ROUTES.SETTLE_EXPENSES,
  MANAGE_GROUPS: CLIENT_STATIC_ROUTES.MANAGE_GROUPS,
  GROUP_SETTINGS: CLIENT_STATIC_ROUTES.GROUP_SETTINGS,
};

const NAV_LINKS = {
  EXPENSE: TO_EXPENSE,
  PAYMENT: TO_PAYMENT,
  MEMBERS: TO_MEMBERS,
  GROUP: TO_GROUP_ACTIONS,
  STATIC: TO_STATIC,
};

export default NAV_LINKS;
