import { ROUTE_PARAMS } from "../../../shared/constants/routeParams.js";
import prefixParamsWithColon from "../utils/route/prefixParamsWithColon.js";
import { CLIENT_STATIC_ROUTES } from "./clientStaticRoutesConstants.js";

const DYNAMIC_SEGMENTS = prefixParamsWithColon(ROUTE_PARAMS);

const {
  GROUPCODE_VALIDATOR,
  JOIN_GROUP_DE,
  JOIN_GROUP_EN,
  TUTORIAL,
  SHARE_GROUP,
  LEAVE_GROUP,
  EXPENSE_DETAILS,
  PAYMENT_DETAILS,
  MEMBER_DETAILS,
  MEMBER_TRANSACTION_HISTORY,
  UPDATE_EXPENSE,
  UPDATE_PAYMENT,
  CONTACT,
} = CLIENT_STATIC_ROUTES;

const {
  GROUP_CODE,
  INITIAL_GROUP_NAME,
  GROUP_NAME,
  ITEM_ID,
  USER_ID,
  EXPENSE_ID,
  PAYMENT_ID,
} = DYNAMIC_SEGMENTS;

export const CLIENT_DYNAMIC_ROUTES = {
  GROUPCODE_VALIDATOR: `${GROUPCODE_VALIDATOR}/${GROUP_CODE}`,

  JOIN_GROUP_DE: `${JOIN_GROUP_DE}/${INITIAL_GROUP_NAME}/${GROUP_CODE}`,
  JOIN_GROUP_EN: `${JOIN_GROUP_EN}/${INITIAL_GROUP_NAME}/${GROUP_CODE}`,

  TUTORIAL: `${TUTORIAL}/${INITIAL_GROUP_NAME}/${GROUP_CODE}`,
  SHARE_GROUP: `${SHARE_GROUP}/${INITIAL_GROUP_NAME}/${GROUP_CODE}`,
  LEAVE_GROUP: `${LEAVE_GROUP}/${GROUP_NAME}/${GROUP_CODE}`,

  EXPENSE_DETAILS: `${EXPENSE_DETAILS}/${GROUP_CODE}/${ITEM_ID}`,
  PAYMENT_DETAILS: `${PAYMENT_DETAILS}/${GROUP_CODE}/${ITEM_ID}`,

  MEMBER_DETAILS: `${MEMBER_DETAILS}/${GROUP_CODE}/${USER_ID}`,
  MEMBER_TRANSACTION_HISTORY: `${MEMBER_TRANSACTION_HISTORY}/${GROUP_CODE}/${USER_ID}`,

  UPDATE_EXPENSE: `${UPDATE_EXPENSE}/${GROUP_CODE}/${EXPENSE_ID}`,
  UPDATE_PAYMENT: `${UPDATE_PAYMENT}/${GROUP_CODE}/${PAYMENT_ID}`,

  CONTACT: `${CONTACT}/${GROUP_CODE}`,

  NOT_FOUND: "*",
};
