const VITE_MODES = {
  DEVELOPMENT: "development",
  PRODUCTION: "production",
};

const APP_MODES = {
  [VITE_MODES.DEVELOPMENT]: VITE_MODES.DEVELOPMENT,
  [VITE_MODES.PRODUCTION]: VITE_MODES.PRODUCTION,
};

const CONFIG_MODES = {
  VITE: VITE_MODES,
  APP: APP_MODES,
};

export default CONFIG_MODES;
