const VIEW_TYPES = {
  HISTORY: "history",
  BALANCES: "balances",
};

const LEGACY_VIEW_TYPES = {
  VIEW_1: "view1",
  VIEW_2: "view2",
};

const HISTORY_VIEWS = [VIEW_TYPES.HISTORY, LEGACY_VIEW_TYPES.VIEW_1];
const BALANCE_VIEWS = [VIEW_TYPES.BALANCES, LEGACY_VIEW_TYPES.VIEW_2];

const VIEWS = {
  TYPES: VIEW_TYPES,
  LEGACY: LEGACY_VIEW_TYPES,
  HISTORY_COLLECTION: HISTORY_VIEWS,
  BALANCE_COLLECTION: BALANCE_VIEWS,
};

export default VIEWS;
