// React and Third-Party Libraries
import axios from "axios";
import { devLog } from "../../../server/utils/errorUtils";

import { API_URL } from "@client-constants/apiConstants";
/**
 * Verifies the solution generated by Friendly Captcha from the client with the Friendly Captcha API.
 * @param {string} solution - The solution generated by Friendly Captcha.
 * @param {string} secret - The API key (obtained from Friendly Captcha) used for verification.
 * @returns {Promise<Object>} - A promise that resolves with the verification result.
 * @throws {Error} - If there is an error during the verification process.
 */
const verifyFriendlyCaptchaSolution = async (solution, secret) => {
  try {
    devLog("Started verifying Friendly Captcha solution.");
    const response = await axios.post(`${API_URL}/captchas/verify-captcha`, {
      solution,
      secret,
    });
    devLog("CaptchaVerified:", response);
    return response.data;
  } catch (error) {
    // Log the error in production for monitoring
    console.error("Error verifying captcha:", error);
    throw error;
  }
};

export default verifyFriendlyCaptchaSolution;
