const ERROR_CODES = {
  GROUP: {
    NOT_FOUND: "ERROR_GROUP_NOT_FOUND",
    NAME_TOO_LONG: "ERROR_GROUP_NAME_TOO_LONG",
    NAME_TOO_SHORT: "ERROR_GROUP_NAME_TOO_SHORT",
  },
  AUTHENTICATION: {
    UNAUTHORIZED: "ERROR_AUTHENTICATION_UNAUTHORIZED",
    FORBIDDEN: "ERROR_AUTHENTICATION_FORBIDDEN",
  },
  MEMBER: {
    NAME_REQUIRED: "ERROR_MEMBER_NAME_REQUIRED",
    NOT_FOUND: "ERROR_MEMBER_NOT_FOUND",
  },
  EXPENSE: {
    DESCRIPTION_REQUIRED: "ERROR_EXPENSE_DESCRIPTION_REQUIRED",
    DESCRIPTION_TOO_SHORT: "ERROR_EXPENSE_DESCRIPTION_TOO_SHORT",
    DESCRIPTION_TOO_LONG: "ERROR_EXPENSE_DESCRIPTION_TOO_LONG",
    AMOUNT_REQUIRED: "ERROR_EXPENSE_AMOUNT_REQUIRED",
    AMOUNT_TOO_LOW: "ERROR_EXPENSE_AMOUNT_TOO_LOW",
    AMOUNT_TOO_HIGH: "ERROR_EXPENSE_AMOUNT_TOO_HIGH",
    PAYER_REQUIRED: "ERROR_EXPENSE_PAYER_REQUIRED",
    BENEFICIARY_REQUIRED: "ERROR_EXPENSE_BENEFICIARY_REQUIRED",
  },
  PAYMENT: {
    MAKER_REQUIRED: "ERROR_PAYMENT_MAKER_REQUIRED",
    RECIPIENT_REQUIRED: "ERROR_PAYMENT_RECIPIENT_REQUIRED",
    AMOUNT_REQUIRED: "ERROR_PAYMENT_AMOUNT_REQUIRED",
    AMOUNT_TOO_LOW: "ERROR_PAYMENT_AMOUNT_TOO_LOW",
  },
  GENERIC: {
    INTERNAL_SERVER_ERROR: "ERROR_INTERNAL_SERVER_ERROR",
    UNEXPECTED_ERROR: "ERROR_UNEXPECTED_ERROR",
  },
};

export default ERROR_CODES;
