const PWA_PROMPT_RESHOW_THRESHOLD_MS = 7 * 24 * 60 * 60 * 1000;

const POLLING_INTERVAL_MS = 30 * 1000;

const SORT_ORDER = {
  ASCENDING: "ascending",
  DESCENDING: "descending",
};

const SYSTEM = {
  PWA_THRESHOLD: PWA_PROMPT_RESHOW_THRESHOLD_MS,
  POLLING_INTERVAL: POLLING_INTERVAL_MS,
  SORT_ORDER,
};

export default SYSTEM;
