const PWA_PROMPT_RESHOW_THRESHOLD_MS = 7 * 24 * 60 * 60 * 1000; // 1 week
const POLLING_INTERVAL_MS = 30 * 1000; // 30 seconds
const GROUP_INACTIVITY_THRESHOLD_DAYS = 90;
const BALANCE_THRESHOLD = 0.01;
const MINIMUM_VALID_TRANSACTION_AMOUNT = 0.01;
const GROUP_CODE_LENGTH = 6;
const GROUP_CODE_ALPHABET = "ACDEFGHJKLMNPQRSTUVWXYZ346789";

const SORT_ORDER = {
  ASCENDING: "ascending",
  DESCENDING: "descending",
};

const SYSTEM = {
  PWA_PROMPT_RESHOW_THRESHOLD_MS,
  POLLING_INTERVAL_MS,
  GROUP_INACTIVITY_THRESHOLD_DAYS,
  BALANCE_THRESHOLD,
  MINIMUM_VALID_TRANSACTION_AMOUNT,
  GROUP_CODE_LENGTH,
  GROUP_CODE_ALPHABET,
  SORT_ORDER,
};

export default SYSTEM;
