const GROUP_CODE_LENGTH = 15;
const GROUP_CODE_ALPHABET = "ACDEFGHJKLMNPQRSTUVWXYZ346789";
const GROUP_INACTIVITY_THRESHOLD_DAYS = 90;

const POLLING_INTERVAL_MS = 30 * 1000; // 30 seconds

const PWA_PROMPT_RESHOW_THRESHOLD_MS = 7 * 24 * 60 * 60 * 1000; // 1 week

const BALANCE_THRESHOLD = 0.01;
const MINIMUM_VALID_TRANSACTION_AMOUNT = 0.01;

const RATE_LIMIT_LAX_WINDOW_MS = 15 * 60 * 1000; // 15 minutes
const RATE_LIMIT_LAX_MAX_REQUESTS = 1000;

const DATA_PURGE_EXCLUDED_GROUP_CODES = ["TEST123"];
const DATA_PURGE_CRON_SCHEDULE = "0 3 * * *"; // Every day at 3:00 AM (server time)
const SERVER_TIMEZONE = "Europe/Paris";

const SORT_ORDER = {
  ASCENDING: "ascending",
  DESCENDING: "descending",
};

const SYSTEM = {
  PWA_PROMPT_RESHOW_THRESHOLD_MS,
  POLLING_INTERVAL_MS,
  GROUP_INACTIVITY_THRESHOLD_DAYS,
  BALANCE_THRESHOLD,
  MINIMUM_VALID_TRANSACTION_AMOUNT,
  GROUP_CODE_LENGTH,
  GROUP_CODE_ALPHABET,
  RATE_LIMIT_LAX_WINDOW_MS,
  RATE_LIMIT_LAX_MAX_REQUESTS,
  DATA_PURGE_EXCLUDED_GROUP_CODES,
  DATA_PURGE_CRON_SCHEDULE,
  SERVER_TIMEZONE,
  SORT_ORDER,
};

export default SYSTEM;
