export const DEFAULT_CURRENCY = "€";

export const CURRENCIES = [
  { value: "EUR", label: "Euro", symbol: "€" },
  { value: "USD", label: "US Dollar", symbol: "$" },
  { value: "GBP", label: "British Pound Sterling", symbol: "£" },
  { value: "AED", label: "United Arab Emirates Dirham", symbol: "dh" },
  { value: "ALL", label: "Albanian Lek", symbol: "L" },
  { value: "AMD", label: "Armenian Dram", symbol: "֏" },
  { value: "ANG", label: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { value: "AOA", label: "Angolan Kwanza", symbol: "Kz" },
  { value: "ARS", label: "Argentine Peso", symbol: "$" },
  { value: "AUD", label: "Australian Dollar", symbol: "$" },
  { value: "AWG", label: "Aruban Florin", symbol: "ƒ" },
  { value: "AZN", label: "Azerbaijani Manat", symbol: "₼" },
  { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { value: "BBD", label: "Barbadian Dollar", symbol: "$" },
  { value: "BDT", label: "Bangladeshi Taka", symbol: "৳" },
  { value: "BGN", label: "Bulgarian Lev", symbol: "лв" },
  { value: "BHD", label: "Bahraini Dinar", symbol: ".د.ب" },
  { value: "BIF", label: "Burundian Franc", symbol: "FBu" },
  { value: "BMD", label: "Bermudian Dollar", symbol: "$" },
  { value: "BND", label: "Brunei Dollar", symbol: "$" },
  { value: "BOB", label: "Bolivian Boliviano", symbol: "Bs." },
  { value: "BRL", label: "Brazilian Real", symbol: "R$" },
  { value: "BSD", label: "Bahamian Dollar", symbol: "$" },
  { value: "BTN", label: "Bhutanese Ngultrum", symbol: "Nu." },
  { value: "BWP", label: "Botswana Pula", symbol: "P" },
  { value: "BYN", label: "Belarusian Ruble", symbol: "Br" },
  { value: "BZD", label: "Belize Dollar", symbol: "BZ$" },
  { value: "CAD", label: "Canadian Dollar", symbol: "$" },
  { value: "CDF", label: "Congolese Franc", symbol: "FC" },
  { value: "CHF", label: "Swiss Franc", symbol: "CHF" },
  { value: "CLP", label: "Chilean Peso", symbol: "$" },
  { value: "CNY", label: "Chinese Yuan", symbol: "¥" },
  { value: "COP", label: "Colombian Peso", symbol: "$" },
  { value: "CRC", label: "Costa Rican Colón", symbol: "₡" },
  { value: "CUC", label: "Cuban Convertible Peso", symbol: "$" },
  { value: "CUP", label: "Cuban Peso", symbol: "$" },
  { value: "CVE", label: "Cape Verdean Escudo", symbol: "$" },
  { value: "CZK", label: "Czech Koruna", symbol: "Kč" },
  { value: "DJF", label: "Djiboutian Franc", symbol: "Fdj" },
  { value: "DKK", label: "Danish Krone", symbol: "kr" },
  { value: "DOP", label: "Dominican Peso", symbol: "RD$" },
  { value: "DZD", label: "Algerian Dinar", symbol: "دج" },
  { value: "EGP", label: "Egyptian Pound", symbol: "E£" },
  { value: "ERN", label: "Eritrean Nakfa", symbol: "Nfk" },
  { value: "ETB", label: "Ethiopian Birr", symbol: "Br" },
  { value: "FJD", label: "Fijian Dollar", symbol: "$" },
  { value: "FKP", label: "Falkland Islands Pound", symbol: "£" },
  { value: "FOK", label: "Faroese Króna", symbol: "kr" },
  { value: "GEL", label: "Georgian Lari", symbol: "₾" },
  { value: "GGP", label: "Guernsey Pound", symbol: "£" },
  { value: "GHS", label: "Ghanaian Cedi", symbol: "GH₵" },
  { value: "GIP", label: "Gibraltar Pound", symbol: "£" },
  { value: "GMD", label: "Gambian Dalasi", symbol: "D" },
  { value: "GNF", label: "Guinean Franc", symbol: "FG" },
  { value: "GTQ", label: "Guatemalan Quetzal", symbol: "Q" },
  { value: "GYD", label: "Guyanaese Dollar", symbol: "$" },
  { value: "HKD", label: "Hong Kong Dollar", symbol: "$" },
  { value: "HNL", label: "Honduran Lempira", symbol: "L" },
  { value: "HRK", label: "Croatian Kuna", symbol: "kn" },
  { value: "HTG", label: "Haitian Gourde", symbol: "G" },
  { value: "HUF", label: "Hungarian Forint", symbol: "Ft" },
  { value: "IDR", label: "Indonesian Rupiah", symbol: "Rp" },
  { value: "ILS", label: "Israeli New Shekel", symbol: "₪" },
  { value: "IMP", label: "Manx Pound", symbol: "£" },
  { value: "INR", label: "Indian Rupee", symbol: "₹" },
  { value: "IQD", label: "Iraqi Dinar", symbol: "د.ع" },
  { value: "IRR", label: "Iranian Rial", symbol: "﷼" },
  { value: "ISK", label: "Icelandic Króna", symbol: "kr" },
  { value: "JEP", label: "Jersey Pound", symbol: "£" },
  { value: "JMD", label: "Jamaican Dollar", symbol: "J$" },
  { value: "JOD", label: "Jordanian Dinar", symbol: "JD" },
  { value: "JPY", label: "Japanese Yen", symbol: "¥" },
  { value: "KES", label: "Kenyan Shilling", symbol: "KSh" },
  { value: "KGS", label: "Kyrgyzstani Som", symbol: "с" },
  { value: "KHR", label: "Cambodian Riel", symbol: "៛" },
  { value: "KID", label: "Kiribati Dollar", symbol: "$" },
  { value: "KMF", label: "Comorian Franc", symbol: "CF" },
  { value: "KPW", label: "North Korean Won", symbol: "₩" },
  { value: "KRW", label: "South Korean Won", symbol: "₩" },
  { value: "KWD", label: "Kuwaiti Dinar", symbol: "KD" },
  { value: "KYD", label: "Cayman Islands Dollar", symbol: "$" },
  { value: "KZT", label: "Kazakhstani Tenge", symbol: "₸" },
  { value: "LAK", label: "Lao Kip", symbol: "₭" },
  { value: "LBP", label: "Lebanese Pound", symbol: "L£" },
  { value: "LKR", label: "Sri Lankan Rupee", symbol: "Rs" },
  { value: "LRD", label: "Liberian Dollar", symbol: "$" },
  { value: "LSL", label: "Lesotho Loti", symbol: "L" },
  { value: "LYD", label: "Libyan Dinar", symbol: "LD" },
  { value: "MAD", label: "Moroccan Dirham", symbol: "dh" },
  { value: "MDL", label: "Moldovan Leu", symbol: "L" },
  { value: "MGA", label: "Malagasy Ariary", symbol: "Ar" },
  { value: "MKD", label: "Macedonian Denar", symbol: "ден" },
  { value: "MMK", label: "Myanmar Kyat", symbol: "K" },
  { value: "MNT", label: "Mongolian Tugrik", symbol: "₮" },
  { value: "MOP", label: "Macanese Pataca", symbol: "MOP$" },
  { value: "MRU", label: "Mauritanian Ouguiya", symbol: "UM" },
  { value: "MUR", label: "Mauritian Rupee", symbol: "Rs" },
  { value: "MVR", label: "Maldivian Rufiyaa", symbol: "Rf" },
  { value: "MWK", label: "Malawian Kwacha", symbol: "MK" },
  { value: "MXN", label: "Mexican Peso", symbol: "$" },
  { value: "MYR", label: "Malaysian Ringgit", symbol: "RM" },
  { value: "MZN", label: "Mozambican Metical", symbol: "MT" },
  { value: "NAD", label: "Namibian Dollar", symbol: "$" },
  { value: "NGN", label: "Nigerian Naira", symbol: "₦" },
  { value: "NIO", label: "Nicaraguan Córdoba", symbol: "C$" },
  { value: "NOK", label: "Norwegian Krone", symbol: "kr" },
  { value: "NPR", label: "Nepalese Rupee", symbol: "Rs" },
  { value: "NZD", label: "New Zealand Dollar", symbol: "$" },
  { value: "OMR", label: "Omani Rial", symbol: "﷼" },
  { value: "PAB", label: "Panamanian Balboa", symbol: "B/." },
  { value: "PEN", label: "Peruvian Nuevo Sol", symbol: "S/." },
  { value: "PGK", label: "Papua New Guinean Kina", symbol: "K" },
  { value: "PHP", label: "Philippine Peso", symbol: "₱" },
  { value: "PKR", label: "Pakistani Rupee", symbol: "Rs" },
  { value: "PLN", label: "Polish Zloty", symbol: "zł" },
  { value: "PYG", label: "Paraguayan Guarani", symbol: "Gs" },
  { value: "QAR", label: "Qatari Rial", symbol: "﷼" },
  { value: "RON", label: "Romanian Leu", symbol: "lei" },
  { value: "RSD", label: "Serbian Dinar", symbol: "Дин." },
  { value: "RUB", label: "Russian Ruble", symbol: "₽" },
  { value: "RWF", label: "Rwandan Franc", symbol: "RF" },
  { value: "SAR", label: "Saudi Riyal", symbol: "﷼" },
  { value: "SBD", label: "Solomon Islands Dollar", symbol: "$" },
  { value: "SCR", label: "Seychellois Rupee", symbol: "Rs" },
  { value: "SDG", label: "Sudanese Pound", symbol: "SDG" },
  { value: "SEK", label: "Swedish Krona", symbol: "kr" },
  { value: "SGD", label: "Singapore Dollar", symbol: "$" },
  { value: "SHP", label: "Saint Helena Pound", symbol: "£" },
  { value: "SLL", label: "Sierra Leonean Leone", symbol: "Le" },
  { value: "SOS", label: "Somali Shilling", symbol: "S" },
  { value: "SRD", label: "Surinamese Dollar", symbol: "$" },
  { value: "SSP", label: "South Sudanese Pound", symbol: "£" },
  { value: "STN", label: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { value: "SYP", label: "Syrian Pound", symbol: "£" },
  { value: "SZL", label: "Swazi Lilangeni", symbol: "L" },
  { value: "THB", label: "Thai Baht", symbol: "฿" },
  { value: "TJS", label: "Tajikistani Somoni", symbol: "SM" },
  { value: "TMT", label: "Turkmenistani Manat", symbol: "m" },
  { value: "TND", label: "Tunisian Dinar", symbol: "DT" },
  { value: "TOP", label: "Tongan Pa'anga", symbol: "T$" },
  { value: "TRY", label: "Turkish Lira", symbol: "₺" },
  { value: "TTD", label: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { value: "TVD", label: "Tuvaluan Dollar", symbol: "$" },
  { value: "TWD", label: "New Taiwan Dollar", symbol: "NT$" },
  { value: "TZS", label: "Tanzanian Shilling", symbol: "TSh" },
  { value: "UAH", label: "Ukrainian Hryvnia", symbol: "₴" },
  { value: "UGX", label: "Ugandan Shilling", symbol: "USh" },
  { value: "UYU", label: "Uruguayan Peso", symbol: "$U" },
  { value: "UZS", label: "Uzbekistan Som", symbol: "so'm" },
  { value: "VES", label: "Venezuelan Bolívar", symbol: "Bs" },
  { value: "VND", label: "Vietnamese Dong", symbol: "₫" },
  { value: "VUV", label: "Vanuatu Vatu", symbol: "VT" },
  { value: "WST", label: "Samoan Tala", symbol: "WS$" },
  { value: "XAF", label: "Central African CFA Franc", symbol: "FCFA" },
  { value: "XCD", label: "East Caribbean Dollar", symbol: "$" },
  { value: "XOF", label: "West African CFA Franc", symbol: "CFA" },
  { value: "XPF", label: "CFP Franc", symbol: "₣" },
  { value: "YER", label: "Yemeni Rial", symbol: "﷼" },
  { value: "ZAR", label: "South African Rand", symbol: "R" },
  { value: "ZMW", label: "Zambian Kwacha", symbol: "ZK" },
  { value: "ZWL", label: "Zimbabwean Dollar", symbol: "$" },
];
